source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby "2.7.8"

gem "rails", "~> 7.0.8", ">= 7.0.8.4"
gem "sqlite3", "~> 1.4.2"
gem "sprockets-rails"
gem "puma", "~> 5.0"
gem 'importmap-rails', '~> 1.0'
gem "turbo-rails"
gem "stimulus-rails"
gem "jbuilder"
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]
gem "bootsnap", require: false
gem 'saude_ruby', git: 'https://github.com/desenvolvendo-me/aplicativos', branch: 'main', glob: 'saude_ruby/*.gemspec'

group :development, :test do
  gem "debug", platforms: %i[ mri mingw x64_mingw ]
  gem 'rspec-rails', '~> 6.0'
  gem 'readapt'
end

group :development do
  gem "web-console"
end

group :test do
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
